import Head from "next/head";
import CameraView from "@/components/camera";

export default function Home() {
  return (
    <>
      <Head>
        <title>Camera Obscura</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CameraView></CameraView>
      </main>
    </>
  );
}
